# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yates/software/minimal-js-runtime

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yates/software/minimal-js-runtime

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yates/software/minimal-js-runtime/CMakeFiles /home/yates/software/minimal-js-runtime/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yates/software/minimal-js-runtime/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runtime

# Build rule for target.
runtime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runtime
.PHONY : runtime

# fast build rule for target.
runtime/fast:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/build
.PHONY : runtime/fast

api/cli.o: api/cli.c.o

.PHONY : api/cli.o

# target to build an object file
api/cli.c.o:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/cli.c.o
.PHONY : api/cli.c.o

api/cli.i: api/cli.c.i

.PHONY : api/cli.i

# target to preprocess a source file
api/cli.c.i:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/cli.c.i
.PHONY : api/cli.c.i

api/cli.s: api/cli.c.s

.PHONY : api/cli.s

# target to generate assembly for a file
api/cli.c.s:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/cli.c.s
.PHONY : api/cli.c.s

api/modules.o: api/modules.c.o

.PHONY : api/modules.o

# target to build an object file
api/modules.c.o:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/modules.c.o
.PHONY : api/modules.c.o

api/modules.i: api/modules.c.i

.PHONY : api/modules.i

# target to preprocess a source file
api/modules.c.i:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/modules.c.i
.PHONY : api/modules.c.i

api/modules.s: api/modules.c.s

.PHONY : api/modules.s

# target to generate assembly for a file
api/modules.c.s:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/modules.c.s
.PHONY : api/modules.c.s

api/runtime.o: api/runtime.c.o

.PHONY : api/runtime.o

# target to build an object file
api/runtime.c.o:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/runtime.c.o
.PHONY : api/runtime.c.o

api/runtime.i: api/runtime.c.i

.PHONY : api/runtime.i

# target to preprocess a source file
api/runtime.c.i:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/runtime.c.i
.PHONY : api/runtime.c.i

api/runtime.s: api/runtime.c.s

.PHONY : api/runtime.s

# target to generate assembly for a file
api/runtime.c.s:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/runtime.c.s
.PHONY : api/runtime.c.s

api/std.o: api/std.c.o

.PHONY : api/std.o

# target to build an object file
api/std.c.o:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/std.c.o
.PHONY : api/std.c.o

api/std.i: api/std.c.i

.PHONY : api/std.i

# target to preprocess a source file
api/std.c.i:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/std.c.i
.PHONY : api/std.c.i

api/std.s: api/std.c.s

.PHONY : api/std.s

# target to generate assembly for a file
api/std.c.s:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/std.c.s
.PHONY : api/std.c.s

api/utils.o: api/utils.c.o

.PHONY : api/utils.o

# target to build an object file
api/utils.c.o:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/utils.c.o
.PHONY : api/utils.c.o

api/utils.i: api/utils.c.i

.PHONY : api/utils.i

# target to preprocess a source file
api/utils.c.i:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/utils.c.i
.PHONY : api/utils.c.i

api/utils.s: api/utils.c.s

.PHONY : api/utils.s

# target to generate assembly for a file
api/utils.c.s:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/utils.c.s
.PHONY : api/utils.c.s

api/version.o: api/version.c.o

.PHONY : api/version.o

# target to build an object file
api/version.c.o:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/version.c.o
.PHONY : api/version.c.o

api/version.i: api/version.c.i

.PHONY : api/version.i

# target to preprocess a source file
api/version.c.i:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/version.c.i
.PHONY : api/version.c.i

api/version.s: api/version.c.s

.PHONY : api/version.s

# target to generate assembly for a file
api/version.c.s:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/api/version.c.s
.PHONY : api/version.c.s

src/fib.o: src/fib.c.o

.PHONY : src/fib.o

# target to build an object file
src/fib.c.o:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/fib.c.o
.PHONY : src/fib.c.o

src/fib.i: src/fib.c.i

.PHONY : src/fib.i

# target to preprocess a source file
src/fib.c.i:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/fib.c.i
.PHONY : src/fib.c.i

src/fib.s: src/fib.c.s

.PHONY : src/fib.s

# target to generate assembly for a file
src/fib.c.s:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/fib.c.s
.PHONY : src/fib.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/main.c.s
.PHONY : src/main.c.s

src/timer.o: src/timer.c.o

.PHONY : src/timer.o

# target to build an object file
src/timer.c.o:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/timer.c.o
.PHONY : src/timer.c.o

src/timer.i: src/timer.c.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.c.i:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/timer.c.i
.PHONY : src/timer.c.i

src/timer.s: src/timer.c.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.c.s:
	$(MAKE) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/timer.c.s
.PHONY : src/timer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... runtime"
	@echo "... api/cli.o"
	@echo "... api/cli.i"
	@echo "... api/cli.s"
	@echo "... api/modules.o"
	@echo "... api/modules.i"
	@echo "... api/modules.s"
	@echo "... api/runtime.o"
	@echo "... api/runtime.i"
	@echo "... api/runtime.s"
	@echo "... api/std.o"
	@echo "... api/std.i"
	@echo "... api/std.s"
	@echo "... api/utils.o"
	@echo "... api/utils.i"
	@echo "... api/utils.s"
	@echo "... api/version.o"
	@echo "... api/version.i"
	@echo "... api/version.s"
	@echo "... src/fib.o"
	@echo "... src/fib.i"
	@echo "... src/fib.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

